inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/
Rails:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: rails
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/WordArray:
  EnforcedStyle: brackets
Style/SymbolArray:
  EnforcedStyle: brackets
Metrics/LineLength:
  Max: 120
Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
Rails/OutputSafety:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
