# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29a9f003ad1f4cb443ce8527d78104a1bdde6a7f6436c2de1bf69909b64674af212d268a77caca0376592c4d001f5cc48403a15b97f9d6eceba6b1c440658f7

test:
  secret_key_base: 791742bfcd61c113d7d957440463fbd15eeb66340931bebad44686aafdd4846ff69105144723b298bf3315c87ab6214d3dca9484d25eddbe413bfbdbba7caa30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
